server:
  port: 8502
spring:
  application:
    name: consul-gateway
  cloud:
    consul:
      discovery:
        healthCheckInterval: 3s
        healthCheckPath: /actuator/health
        hostname: 192.168.9.52
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        register: true
        serviceName: ${spring.application.name}
        tags: url-prefix-/${spring.application.name}
      enabled: true
      host: 192.168.8.227
      port: 8500
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        -   filters:
              - StripPrefix=1
            id: java
            predicates:
              - Path=/java/**
            uri: lb://consul-java
        -   filters:
              - StripPrefix=1
            id: go
            predicates:
              - Path=/go/**
            uri: lb://consul-go
        -   filters:
              - StripPrefix=1
            id: python
            predicates:
              - Path=/python/**
            uri: lb://consul-py
#        -   filters:
#              - StripPrefix=1
#            id: baidu
#            predicates:
#              - Path=/baidu
#            uri: https://www.baidu.com

